// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okbcotwchighrkgwbrtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rYmNvdHdjaGlnaHJrZ3dicnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjY0ODksImV4cCI6MjA1ODcwMjQ4OX0.5l5BdxxT2ebI_nAAgUoVR4-YFOL3ied3RuspPuHyKkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);