// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjydzlatucrbbtzscwbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqeWR6bGF0dWNyYmJ0enNjd2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NTQ2ODMsImV4cCI6MjA1NzAzMDY4M30.ROrDWmBdDgUkkdcX6aSlrF8LPKcWL9UEKvCfh61Pe-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);